general:
  buildTool: "npm"
steps:
  mtaBuild:
    applicationName: 'Test'
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'sndbox'
      space: 'Piper-Dev'
      credentialsId: 'CF_CREDENTIALSID'
