general:
  buildTool: 'mta'
steps:
  mtaBuild:
    buildTarget: 'CF'

  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: 'sndbox'
      space: 'Piper-Dev'
      credentialsId: 'CF_CREDENTIALSID'